from enum import Enum


class Event(Enum):
    first_launch = 0,
    unknown_command = 1,
    help = 2,
    search_select_server = 3,
    search_select_race = 4,
    db_error = 5,
    no_lots_found = 6,
    filtered_lots_found = 7,
    sell_menu = 8,
    new_lot_input_server = 9,
    new_lot_input_race = 10,
    new_lot_input_class = 11,
    invalid_value = 12
    new_lot_input_lvl = 13,
    new_lot_input_heaven = 14,
    new_lot_input_doll = 15,
    new_lot_input_description = 16,
    new_lot_input_price = 17,
    new_lot_input_contacts = 18,
    new_lot_success = 19,
    new_lot_fail = 20,
    lot_info_button_template = 21,
    show_lots_indices = 22,
    lot_info_template = 23,
    no_user_lots_found = 24,
    close_lot = 25,
    close_lot_confirm = 26,
    close_lot_success = 27,
    select_date = 28,
    lots_visit_data = 29,
    filter_menu = 30,
    input_min_lvl = 31,
    input_max_lvl = 32,
    input_min_price = 33,
    input_max_price = 34,
    found_favs = 35,
    no_favs = 36,
    seller_lots = 37,
